# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a8bd50b529806e256fd407d5d6ff502b301e4d1ef2dac9af32ce105b952696e726f27c149e6634750c76361068a090f9f567f708d47cc82e2f314bcd53d9999

test:
  secret_key_base: e5317f9e45f7544e31f596d2ee47ad998a8bed2e283d712223ce493a91d1828aa94c43fec03bac5fa370111cd3a6ddcd9a996b8c6edfb3b04ae8a14ccbfc8aac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
